import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers"; // Mantenha a importação

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={` antialiased bg-gray-50`}>
        {/* Coloque o Providers aqui, dentro do body */}
        <Providers>
          <nav className="w-full bg-blue-700 text-white py-4 px-8 flex justify-between items-center shadow">
            <div className="font-bold text-xl">Certificadora</div>
            <div>
              <a href="/palestra" className="hover:underline font-medium">Palestra</a>
            </div>
          </nav>
          <main className="min-h-[80vh]">{children}</main>
          <footer className="w-full bg-blue-700 text-white py-4 px-8 text-center mt-8">
            &copy; {new Date().getFullYear()} Certificadora. Todos os direitos reservados.
          </footer>
        </Providers>
      </body>
    </html>
  );
}